__author__ = 'kutepoval'
from currency.models import *


ROWS = 5 #кол-во строк для отображения валюты
COLUMNS = 7 #кол-во столбцов для отображения валюты


CURRENCY_CLASSES = {
    "USD":USD_RUB,
    "EUR":EUR_RUB,
    "AUD":AUD_RUB,
    "AZN":AZN_RUB,
    "AMD":AMD_RUB,
    "BYR":BYR_RUB,
    "BGN":BGN_RUB,
    "BRL":BRL_RUB,
    "HUF":HUF_RUB,
    "KRW":KRW_RUB,
    "DKK":DKK_RUB,
    "INR":INR_RUB,
    "KZT":KZT_RUB,
    "CAD":CAD_RUB,
    "KGS":KGS_RUB,
    "CNY":CNY_RUB,
    "LVL":LVL_RUB,
    "LTL":LTL_RUB,
    "MDL":MDL_RUB,
    "RON":RON_RUB,
    "TMT":TMT_RUB,
    "NOK":NOK_RUB,
    "PLN":PLN_RUB,
    "XDR":XDR_RUB,
    "SGD":SGD_RUB,
    "TJS":TJS_RUB,
    "TRY":TRY_RUB,
    "UZS":UZS_RUB,
    "UAH":UAH_RUB,
    "GBP":GBP_RUB,
    "CZK":CZK_RUB,
    "SEK":SEK_RUB,
    "CHF":CHF_RUB,
    "ZAR":ZAR_RUB,
    "JPY":JPY_RUB,
}

#Неизменяющиеся данные о валютах
CURRENCY_DATA = (
    {"class":USD_RUB, "char_code":"USD", "name":"Доллар США", "code":"840"},
    {"class":EUR_RUB, "char_code":"EUR", "name":"Евро", "code":"978"},
    {"class":AUD_RUB, "char_code":"AUD", "name":"Австралийский доллар", "code":"036"},
    {"class":AZN_RUB, "char_code":"AZN", "name":"Азербайджанский манат", "code":"944"},
    {"class":AMD_RUB, "char_code":"AMD", "name":"Армянский драм", "code":"051"},
    {"class":BYR_RUB, "char_code":"BYR", "name":"Белорусский рубль", "code":"974"},
    {"class":BGN_RUB, "char_code":"BGN", "name":"Болгарский лев", "code":"975"},
    {"class":BRL_RUB, "char_code":"BRL", "name":"Бразильский реал", "code":"986"},
    {"class":HUF_RUB, "char_code":"HUF", "name":"Венгерский форинт", "code":"348"},
    {"class":KRW_RUB, "char_code":"KRW", "name":"Вон Республики Корея", "code":"410"},
    {"class":DKK_RUB, "char_code":"DKK", "name":"Датская крона", "code":"208"},
    {"class":INR_RUB, "char_code":"INR", "name":"Индийский рупий", "code":"356"},
    {"class":KZT_RUB, "char_code":"KZT", "name":"Казахстанский тенге", "code":"398"},
    {"class":CAD_RUB, "char_code":"CAD", "name":"Канадский доллар", "code":"124"},
    {"class":KGS_RUB, "char_code":"KGS", "name":"Киргизский сом", "code":"417"},
    {"class":CNY_RUB, "char_code":"CNY", "name":"Китайский юань", "code":"156"},
    #{"class":LVL_RUB, "char_code":"LVL", "name":"Латвийский лат", "code":"428"},
    {"class":LTL_RUB, "char_code":"LTL", "name":"Литовский лит", "code":"440"},
    {"class":MDL_RUB, "char_code":"MDL", "name":"Молдавский лей", "code":"498"},
    {"class":RON_RUB, "char_code":"RON", "name":"Румынский лей", "code":"946"},
    {"class":TMT_RUB, "char_code":"TMT", "name":"Туркменский манат", "code":"934"},
    {"class":NOK_RUB, "char_code":"NOK", "name":"Норвежская крона", "code":"578"},
    {"class":PLN_RUB, "char_code":"PLN", "name":"Польский злотый", "code":"985"},
    {"class":XDR_RUB, "char_code":"XDR", "name":"СДР", "code":"960"},
    {"class":SGD_RUB, "char_code":"SGD", "name":"Сингапурский доллар", "code":"702"},
    {"class":TJS_RUB, "char_code":"TJS", "name":"Таджикский сомони", "code":"972"},
    {"class":TRY_RUB, "char_code":"TRY", "name":"Турецкая лира", "code":"949"},
    {"class":UZS_RUB, "char_code":"UZS", "name":"Узбекский сум", "code":"860"},
    {"class":UAH_RUB, "char_code":"UAH", "name":"Украинская гривна", "code":"980"},
    {"class":GBP_RUB, "char_code":"GBP", "name":"Фунт стерлингов", "code":"826"},
    {"class":CZK_RUB, "char_code":"CZK", "name":"Чешская крона", "code":"203"},
    {"class":SEK_RUB, "char_code":"SEK", "name":"Шведская крона", "code":"752"},
    {"class":CHF_RUB, "char_code":"CHF", "name":"Швейцарский франк", "code":"756"},
    {"class":ZAR_RUB, "char_code":"ZAR", "name":"Южноафриканский ранд", "code":"710"},
    {"class":JPY_RUB, "char_code":"JPY", "name":"Японская иена", "code":"392"},
)
