from django.contrib import admin
from chart_forecast.models import *

# Register your models here.
admin.site.register(Forecast_of_USD)
admin.site.register(Forecast_of_EUR)
admin.site.register(Forecast_of_AUD)
admin.site.register(Forecast_of_AZN)
admin.site.register(Forecast_of_AMD)
admin.site.register(Forecast_of_BYR)
admin.site.register(Forecast_of_BGN)
admin.site.register(Forecast_of_BRL)
admin.site.register(Forecast_of_HUF)
admin.site.register(Forecast_of_KRW)
admin.site.register(Forecast_of_DKK)
admin.site.register(Forecast_of_INR)
admin.site.register(Forecast_of_KZT)
admin.site.register(Forecast_of_CAD)
admin.site.register(Forecast_of_KGS)
admin.site.register(Forecast_of_CNY)
admin.site.register(Forecast_of_LVL)
admin.site.register(Forecast_of_LTL)
admin.site.register(Forecast_of_MDL)
admin.site.register(Forecast_of_RON)
admin.site.register(Forecast_of_TMT)
admin.site.register(Forecast_of_NOK)
admin.site.register(Forecast_of_PLN)
admin.site.register(Forecast_of_XDR)
admin.site.register(Forecast_of_SGD)
admin.site.register(Forecast_of_TJS)
admin.site.register(Forecast_of_TRY)
admin.site.register(Forecast_of_UZS)
admin.site.register(Forecast_of_UAH)
admin.site.register(Forecast_of_GBP)
admin.site.register(Forecast_of_CZK)
admin.site.register(Forecast_of_SEK)
admin.site.register(Forecast_of_CHF)
admin.site.register(Forecast_of_ZAR)
admin.site.register(Forecast_of_JPY)
