__author__ = 'kutepoval'

from chart_forecast.models import *

FORECAST_CLASSES = {
    "USD":Forecast_of_USD,
    "EUR":Forecast_of_EUR,
    "AUD":Forecast_of_AUD,
    "AZN":Forecast_of_AZN,
    "AMD":Forecast_of_AMD,
    "BYR":Forecast_of_BYR,
    "BGN":Forecast_of_BGN,
    "BRL":Forecast_of_BRL,
    "HUF":Forecast_of_HUF,
    "KRW":Forecast_of_KRW,
    "DKK":Forecast_of_DKK,
    "INR":Forecast_of_INR,
    "KZT":Forecast_of_KZT,
    "CAD":Forecast_of_CAD,
    "KGS":Forecast_of_KGS,
    "CNY":Forecast_of_CNY,
    "LVL":Forecast_of_LVL,
    "LTL":Forecast_of_LTL,
    "MDL":Forecast_of_MDL,
    "RON":Forecast_of_RON,
    "TMT":Forecast_of_TMT,
    "NOK":Forecast_of_NOK,
    "PLN":Forecast_of_PLN,
    "XDR":Forecast_of_XDR,
    "SGD":Forecast_of_SGD,
    "TJS":Forecast_of_TJS,
    "TRY":Forecast_of_TRY,
    "UZS":Forecast_of_UZS,
    "UAH":Forecast_of_UAH,
    "GBP":Forecast_of_GBP,
    "CZK":Forecast_of_CZK,
    "SEK":Forecast_of_SEK,
    "CHF":Forecast_of_CHF,
    "ZAR":Forecast_of_ZAR,
    "JPY":Forecast_of_JPY,
}
