__author__ = 'Alexey Kutepov'

from forecast.models import *

FORECAST_CLASSES = {
    "USD":USD,
    "EUR":EUR,
    "AUD":AUD,
    "AZN":AZN,
    "AMD":AMD,
    "BYR":BYR,
    "BGN":BGN,
    "BRL":BRL,
    "HUF":HUF,
    "KRW":KRW,
    "DKK":DKK,
    "INR":INR,
    "KZT":KZT,
    "CAD":CAD,
    "KGS":KGS,
    "CNY":CNY,
    "LVL":LVL,
    "LTL":LTL,
    "MDL":MDL,
    "RON":RON,
    "TMT":TMT,
    "NOK":NOK,
    "PLN":PLN,
    "XDR":XDR,
    "SGD":SGD,
    "TJS":TJS,
    "TRY":TRY,
    "UZS":UZS,
    "UAH":UAH,
    "GBP":GBP,
    "CZK":CZK,
    "SEK":SEK,
    "CHF":CHF,
    "ZAR":ZAR,
    "JPY":JPY,
}