__author__ = 'Alexey Kutepov'

from forecast.models import *

FORECAST_CLASSES = {
    "USD":USD_RUB,
    "EUR":EUR_RUB,
    "AUD":AUD_RUB,
    "AZN":AZN_RUB,
    "AMD":AMD_RUB,
    "BYR":BYR_RUB,
    "BGN":BGN_RUB,
    "BRL":BRL_RUB,
    "HUF":HUF_RUB,
    "KRW":KRW_RUB,
    "DKK":DKK_RUB,
    "INR":INR_RUB,
    "KZT":KZT_RUB,
    "CAD":CAD_RUB,
    "KGS":KGS_RUB,
    "CNY":CNY_RUB,
    "LVL":LVL_RUB,
    "LTL":LTL_RUB,
    "MDL":MDL_RUB,
    "RON":RON_RUB,
    "TMT":TMT_RUB,
    "NOK":NOK_RUB,
    "PLN":PLN_RUB,
    "XDR":XDR_RUB,
    "SGD":SGD_RUB,
    "TJS":TJS_RUB,
    "TRY":TRY_RUB,
    "UZS":UZS_RUB,
    "UAH":UAH_RUB,
    "GBP":GBP_RUB,
    "CZK":CZK_RUB,
    "SEK":SEK_RUB,
    "CHF":CHF_RUB,
    "ZAR":ZAR_RUB,
    "JPY":JPY_RUB,
}